// <auto-generated />
using System;
using ExeGrup.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExeGrup.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260101000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExeGrup.Web.Models.AdminUser", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Username").IsUnique();
                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("ExeGrup.Web.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Company").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("FullName").IsRequired().HasMaxLength(150).HasColumnType("TEXT");
                    b.Property<bool>("IsRead").HasColumnType("INTEGER");
                    b.Property<string>("Message").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Phone").IsRequired().HasMaxLength(30).HasColumnType("TEXT");
                    b.Property<string>("Subject").HasMaxLength(300).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("ExeGrup.Web.Models.GalleryImage", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<string>("ImagePath").IsRequired().HasMaxLength(300).HasColumnType("TEXT");
                    b.Property<int>("SortOrder").HasColumnType("INTEGER");
                    b.Property<string>("Title").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<DateTime>("UploadedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("GalleryImages");
                });

            modelBuilder.Entity("ExeGrup.Web.Models.Project", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("ApplicationType").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<string>("CoverImage").HasMaxLength(300).HasColumnType("TEXT");
                    b.Property<DateTime>("Date").HasColumnType("TEXT");
                    b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("IsActive").HasColumnType("INTEGER");
                    b.Property<string>("Material").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("ShortDescription").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(220).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ExeGrup.Web.Models.ProjectImage", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("ImagePath").IsRequired().HasMaxLength(300).HasColumnType("TEXT");
                    b.Property<int>("ProjectId").HasColumnType("INTEGER");
                    b.Property<int>("SortOrder").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("ProjectId");
                    b.ToTable("ProjectImages");
                });

            modelBuilder.Entity("ExeGrup.Web.Models.Service", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Image").HasMaxLength(300).HasColumnType("TEXT");
                    b.Property<bool>("IsActive").HasColumnType("INTEGER");
                    b.Property<string>("SeoDescription").HasMaxLength(300).HasColumnType("TEXT");
                    b.Property<string>("SeoTitle").HasMaxLength(200).HasColumnType("TEXT");
                    b.Property<string>("ShortDescription").IsRequired().HasMaxLength(400).HasColumnType("TEXT");
                    b.Property<int>("SortOrder").HasColumnType("INTEGER");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(170).HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasMaxLength(150).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("Services");
                });

            modelBuilder.Entity("ExeGrup.Web.Models.SiteSetting", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Key").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                    b.Property<string>("Value").HasMaxLength(4000).HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Key").IsUnique();
                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("ExeGrup.Web.Models.ProjectImage", b =>
                {
                    b.HasOne("ExeGrup.Web.Models.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Project");
                });

            modelBuilder.Entity("ExeGrup.Web.Models.Project", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}